// <auto-generated />
using System;
using DemoApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoApp.Migrations
{
    [DbContext(typeof(PharmacyContext))]
    partial class PharmacyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoApp.Models.Depot", b =>
                {
                    b.Property<Guid>("DepotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DepotId");

                    b.ToTable("Depots");
                });

            modelBuilder.Entity("DemoApp.Models.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SiteDoctor")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SiteNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.HasKey("SiteId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("DemoApp.Models.Subject", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("DemoApp.Models.Unit", b =>
                {
                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Data");

                    b.HasIndex("SiteId");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("DemoApp.Models.Unit", b =>
                {
                    b.HasOne("DemoApp.Models.Site", null)
                        .WithMany("MedicationUnits")
                        .HasForeignKey("SiteId");
                });
#pragma warning restore 612, 618
        }
    }
}
